#!/usr/bin/env bash

set -eu

Ec2ppukuLimit=${Ec2ppukuLimit:-90}

df=$(df)

for drive in $(echo "$df" | grep -E '^/' | awk '{print $1}'); do
    free=$(echo "$df" | grep -E "^$drive" | awk '{print $5}' | grep -oE '[0-9]+')
    if [ "$free" -gt "$Ec2ppukuLimit" ]; then
        echo "$drive use $free% is above ec2ppuku limit $Ec2ppukuLimit%"
        echo "Shutting down..."
        halt
        exit 0
    fi
done

